from __future__ import annotations

from datetime import UTC, datetime
from typing import Literal

from pydantic import BaseModel, Field

Region = Literal["domestic", "overseas"]
ThemeMode = Literal["core", "all"]


class UniverseHolding(BaseModel):
    symbol: str
    name: str
    local_name: str
    market: str
    region: Region
    currency: Literal["KRW", "USD"]
    sector: str
    sector_ko: str
    market_cap_rank: int
    market_cap_bucket: Literal["mega-cap", "large-cap"]


class ThemeUniverse(BaseModel):
    key: str
    name: str
    name_ko: str | None = None
    description: str
    sector: str
    top_market_cap: list[UniverseHolding]


class ThemeUniverseResponse(BaseModel):
    source: str = "MCBot curated universe"
    count: int
    mode: ThemeMode = "core"
    refreshed_at: str
    themes: list[ThemeUniverse]
    notes: list[str] = Field(default_factory=list)


_CORE_THEME_KEYS = (
    "korea-semiconductors",
    "domestic-defense",
    "semiconductors",
    "ai-platforms",
    "us-inverse-etfs",
    "korea-inverse-etfs",
)


def _normalize_theme_mode(mode: str) -> ThemeMode:
    normalized = mode.strip().lower()
    return "all" if normalized == "all" else "core"


THEME_UNIVERSE: tuple[ThemeUniverse, ...] = (
    ThemeUniverse(
        key="semiconductors",
        name="Semiconductors",
        description="Chip designers, foundries, and key equipment names.",
        sector="Technology",
        top_market_cap=[
            UniverseHolding(
                symbol="NVDA",
                name="NVIDIA Corp.",
                local_name="NVIDIA Corp.",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=1,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="AVGO",
                name="Broadcom Inc.",
                local_name="Broadcom Inc.",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=2,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="TSM",
                name="Taiwan Semiconductor",
                local_name="Taiwan Semiconductor",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=3,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="ASML",
                name="ASML Holding",
                local_name="ASML Holding",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=4,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="AMD",
                name="Advanced Micro Devices",
                local_name="Advanced Micro Devices",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=5,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="QCOM",
                name="Qualcomm Inc.",
                local_name="Qualcomm Inc.",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=6,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="TXN",
                name="Texas Instruments",
                local_name="Texas Instruments",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=7,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="MU",
                name="Micron Technology",
                local_name="Micron Technology",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=8,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="AMAT",
                name="Applied Materials",
                local_name="Applied Materials",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=9,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="LRCX",
                name="Lam Research",
                local_name="Lam Research",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=10,
                market_cap_bucket="large-cap",
            ),
        ],
    ),
    ThemeUniverse(
        key="ai-platforms",
        name="AI Platforms",
        description="Model platforms, cloud infrastructure, and workflow software.",
        sector="Technology",
        top_market_cap=[
            UniverseHolding(
                symbol="MSFT",
                name="Microsoft",
                local_name="Microsoft",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=1,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="AMZN",
                name="Amazon",
                local_name="Amazon",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=2,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="GOOGL",
                name="Alphabet Class A",
                local_name="Alphabet Class A",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=3,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="META",
                name="Meta Platforms",
                local_name="Meta Platforms",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=4,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="ORCL",
                name="Oracle",
                local_name="Oracle",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=5,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="CRM",
                name="Salesforce",
                local_name="Salesforce",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=6,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="NOW",
                name="ServiceNow",
                local_name="ServiceNow",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=7,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="ADBE",
                name="Adobe",
                local_name="Adobe",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=8,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="SNOW",
                name="Snowflake",
                local_name="Snowflake",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=9,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="IBM",
                name="IBM",
                local_name="IBM",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=10,
                market_cap_bucket="large-cap",
            ),
        ],
    ),
    ThemeUniverse(
        key="ev-batteries",
        name="EV and Batteries",
        description="Electric vehicle makers, battery tech, and charging infrastructure.",
        sector="Automotive",
        top_market_cap=[
            UniverseHolding(
                symbol="TSLA",
                name="Tesla",
                local_name="Tesla",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=1,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="GM",
                name="General Motors",
                local_name="General Motors",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=2,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="F",
                name="Ford Motor",
                local_name="Ford Motor",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=3,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="NIO",
                name="NIO Inc.",
                local_name="NIO Inc.",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=4,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="XPEV",
                name="XPeng",
                local_name="XPeng",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=5,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="RIVN",
                name="Rivian",
                local_name="Rivian",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=6,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="LCID",
                name="Lucid Group",
                local_name="Lucid Group",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=7,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="QS",
                name="QuantumScape",
                local_name="QuantumScape",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=8,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="BE",
                name="Bloom Energy",
                local_name="Bloom Energy",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=9,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="PLUG",
                name="Plug Power",
                local_name="Plug Power",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=10,
                market_cap_bucket="large-cap",
            ),
        ],
    ),
    ThemeUniverse(
        key="healthcare-innovation",
        name="Healthcare Innovation",
        description="Large-cap healthcare leaders and medical technology names.",
        sector="Healthcare",
        top_market_cap=[
            UniverseHolding(
                symbol="LLY",
                name="Eli Lilly",
                local_name="Eli Lilly",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=1,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="UNH",
                name="UnitedHealth Group",
                local_name="UnitedHealth Group",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=2,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="JNJ",
                name="Johnson & Johnson",
                local_name="Johnson & Johnson",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=3,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="ABBV",
                name="AbbVie",
                local_name="AbbVie",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=4,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="MRK",
                name="Merck",
                local_name="Merck",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=5,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="NVO",
                name="Novo Nordisk",
                local_name="Novo Nordisk",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=6,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="TMO",
                name="Thermo Fisher Scientific",
                local_name="Thermo Fisher Scientific",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=7,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="ISRG",
                name="Intuitive Surgical",
                local_name="Intuitive Surgical",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=8,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="AMGN",
                name="Amgen",
                local_name="Amgen",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=9,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="GILD",
                name="Gilead Sciences",
                local_name="Gilead Sciences",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=10,
                market_cap_bucket="large-cap",
            ),
        ],
    ),
    ThemeUniverse(
        key="korea-semiconductors",
        name="Korea Semiconductors",
        name_ko="국내 반도체",
        description="KOSPI and KOSDAQ semiconductor leaders used by the paper rotation strategy.",
        sector="Technology",
        top_market_cap=[
            UniverseHolding(
                symbol="005930",
                name="Samsung Electronics",
                local_name="삼성전자",
                market="KOSPI",
                region="domestic",
                currency="KRW",
                sector="Korea Semiconductors",
                sector_ko="국내 반도체",
                market_cap_rank=1,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="000660",
                name="SK Hynix",
                local_name="SK하이닉스",
                market="KOSPI",
                region="domestic",
                currency="KRW",
                sector="Korea Semiconductors",
                sector_ko="국내 반도체",
                market_cap_rank=2,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="042700",
                name="Hanmi Semiconductor",
                local_name="한미반도체",
                market="KOSPI",
                region="domestic",
                currency="KRW",
                sector="Korea Semiconductors",
                sector_ko="국내 반도체",
                market_cap_rank=3,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="058470",
                name="Leeno Industrial",
                local_name="리노공업",
                market="KOSDAQ",
                region="domestic",
                currency="KRW",
                sector="Korea Semiconductors",
                sector_ko="국내 반도체",
                market_cap_rank=4,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="403870",
                name="HPSP",
                local_name="HPSP",
                market="KOSDAQ",
                region="domestic",
                currency="KRW",
                sector="Korea Semiconductors",
                sector_ko="국내 반도체",
                market_cap_rank=5,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="039030",
                name="EO Technics",
                local_name="이오테크닉스",
                market="KOSDAQ",
                region="domestic",
                currency="KRW",
                sector="Korea Semiconductors",
                sector_ko="국내 반도체",
                market_cap_rank=6,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="240810",
                name="Wonik IPS",
                local_name="원익IPS",
                market="KOSDAQ",
                region="domestic",
                currency="KRW",
                sector="Korea Semiconductors",
                sector_ko="국내 반도체",
                market_cap_rank=7,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="108320",
                name="LX Semicon",
                local_name="LX세미콘",
                market="KOSPI",
                region="domestic",
                currency="KRW",
                sector="Korea Semiconductors",
                sector_ko="국내 반도체",
                market_cap_rank=8,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="095340",
                name="ISC",
                local_name="ISC",
                market="KOSDAQ",
                region="domestic",
                currency="KRW",
                sector="Korea Semiconductors",
                sector_ko="국내 반도체",
                market_cap_rank=9,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="036930",
                name="Jusung Engineering",
                local_name="주성엔지니어링",
                market="KOSDAQ",
                region="domestic",
                currency="KRW",
                sector="Korea Semiconductors",
                sector_ko="국내 반도체",
                market_cap_rank=10,
                market_cap_bucket="large-cap",
            ),
        ],
    ),
    ThemeUniverse(
        key="domestic-defense",
        name="Domestic Defense",
        name_ko="국내 방산",
        description="Domestic defense primes, shipbuilding, and tactical technology names.",
        sector="Industrials",
        top_market_cap=[
            UniverseHolding(
                symbol="012450",
                name="Hanwha Aerospace",
                local_name="한화에어로스페이스",
                market="KOSPI",
                region="domestic",
                currency="KRW",
                sector="Domestic Defense",
                sector_ko="국내 방산",
                market_cap_rank=1,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="042660",
                name="Hanwha Ocean",
                local_name="한화오션",
                market="KOSPI",
                region="domestic",
                currency="KRW",
                sector="Domestic Defense",
                sector_ko="국내 방산",
                market_cap_rank=2,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="064350",
                name="Hyundai Rotem",
                local_name="현대로템",
                market="KOSPI",
                region="domestic",
                currency="KRW",
                sector="Domestic Defense",
                sector_ko="국내 방산",
                market_cap_rank=3,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="047810",
                name="Korea Aerospace Industries",
                local_name="한국항공우주",
                market="KOSPI",
                region="domestic",
                currency="KRW",
                sector="Domestic Defense",
                sector_ko="국내 방산",
                market_cap_rank=4,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="079550",
                name="LIG Nex1",
                local_name="LIG넥스원",
                market="KOSPI",
                region="domestic",
                currency="KRW",
                sector="Domestic Defense",
                sector_ko="국내 방산",
                market_cap_rank=5,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="272210",
                name="Hanwha Systems",
                local_name="한화시스템",
                market="KOSPI",
                region="domestic",
                currency="KRW",
                sector="Domestic Defense",
                sector_ko="국내 방산",
                market_cap_rank=6,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="103140",
                name="Poongsan",
                local_name="풍산",
                market="KOSPI",
                region="domestic",
                currency="KRW",
                sector="Domestic Defense",
                sector_ko="국내 방산",
                market_cap_rank=7,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="077970",
                name="STX Engine",
                local_name="STX엔진",
                market="KOSPI",
                region="domestic",
                currency="KRW",
                sector="Domestic Defense",
                sector_ko="국내 방산",
                market_cap_rank=8,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="003570",
                name="SNT Dynamics",
                local_name="SNT다이내믹스",
                market="KOSPI",
                region="domestic",
                currency="KRW",
                sector="Domestic Defense",
                sector_ko="국내 방산",
                market_cap_rank=9,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="064960",
                name="SNT Motiv",
                local_name="SNT모티브",
                market="KOSPI",
                region="domestic",
                currency="KRW",
                sector="Domestic Defense",
                sector_ko="국내 방산",
                market_cap_rank=10,
                market_cap_bucket="large-cap",
            ),
        ],
    ),
)


AdditionalHoldingSpec = tuple[
    str,
    str,
    str,
    str,
    Region,
    Literal["KRW", "USD"],
    Literal["mega-cap", "large-cap"],
]


def _additional_theme(
    *,
    key: str,
    name: str,
    name_ko: str,
    description: str,
    sector: str,
    sector_ko: str,
    rows: tuple[AdditionalHoldingSpec, ...],
) -> ThemeUniverse:
    return ThemeUniverse(
        key=key,
        name=name,
        name_ko=name_ko,
        description=description,
        sector=sector,
        top_market_cap=[
            UniverseHolding(
                symbol=symbol,
                name=holding_name,
                local_name=local_name,
                market=market,
                region=region,
                currency=currency,
                sector=name,
                sector_ko=sector_ko,
                market_cap_rank=index,
                market_cap_bucket=bucket,
            )
            for index, (
                symbol,
                holding_name,
                local_name,
                market,
                region,
                currency,
                bucket,
            ) in enumerate(rows, start=1)
        ],
    )


ADDITIONAL_THEME_UNIVERSE: tuple[ThemeUniverse, ...] = (
    _additional_theme(
        key="quantum-computing",
        name="Quantum Computing",
        name_ko="\uc591\uc790\ucef4\ud4e8\ud130",
        description="Quantum hardware, software, and platform leaders for theme momentum tests.",
        sector="Technology",
        sector_ko="\uc591\uc790\ucef4\ud4e8\ud130",
        rows=(
            ("IBM", "IBM", "IBM", "NYSE", "overseas", "USD", "mega-cap"),
            (
                "GOOGL",
                "Alphabet Class A",
                "Alphabet Class A",
                "NASDAQ",
                "overseas",
                "USD",
                "mega-cap",
            ),
            ("MSFT", "Microsoft", "Microsoft", "NASDAQ", "overseas", "USD", "mega-cap"),
            ("IONQ", "IonQ", "IonQ", "NYSE", "overseas", "USD", "large-cap"),
            (
                "RGTI",
                "Rigetti Computing",
                "Rigetti Computing",
                "NASDAQ",
                "overseas",
                "USD",
                "large-cap",
            ),
            ("QBTS", "D-Wave Quantum", "D-Wave Quantum", "NYSE", "overseas", "USD", "large-cap"),
            (
                "QUBT",
                "Quantum Computing Inc.",
                "Quantum Computing Inc.",
                "NASDAQ",
                "overseas",
                "USD",
                "large-cap",
            ),
            ("HON", "Honeywell", "Honeywell", "NASDAQ", "overseas", "USD", "large-cap"),
            ("ARQQ", "Arqit Quantum", "Arqit Quantum", "NASDAQ", "overseas", "USD", "large-cap"),
            (
                "QTUM",
                "Defiance Quantum ETF",
                "Defiance Quantum ETF",
                "NYSEARCA",
                "overseas",
                "USD",
                "large-cap",
            ),
        ),
    ),
    _additional_theme(
        key="power-grid",
        name="Power and Grid",
        name_ko="\uc804\ub825/\uadf8\ub9ac\ub4dc",
        description="Electrical equipment, grid buildout, and power infrastructure names.",
        sector="Industrials",
        sector_ko="\uc804\ub825/\uadf8\ub9ac\ub4dc",
        rows=(
            ("GEV", "GE Vernova", "GE Vernova", "NYSE", "overseas", "USD", "large-cap"),
            ("ETN", "Eaton", "Eaton", "NYSE", "overseas", "USD", "large-cap"),
            ("PWR", "Quanta Services", "Quanta Services", "NYSE", "overseas", "USD", "large-cap"),
            ("VRT", "Vertiv", "Vertiv", "NYSE", "overseas", "USD", "large-cap"),
            ("HUBB", "Hubbell", "Hubbell", "NYSE", "overseas", "USD", "large-cap"),
            ("ABBNY", "ABB ADR", "ABB ADR", "OTC", "overseas", "USD", "large-cap"),
            (
                "SBGSY",
                "Schneider Electric ADR",
                "Schneider Electric ADR",
                "OTC",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "AEP",
                "American Electric Power",
                "American Electric Power",
                "NASDAQ",
                "overseas",
                "USD",
                "large-cap",
            ),
            ("NEE", "NextEra Energy", "NextEra Energy", "NYSE", "overseas", "USD", "large-cap"),
            ("SO", "Southern Company", "Southern Company", "NYSE", "overseas", "USD", "large-cap"),
        ),
    ),
    _additional_theme(
        key="data-centers",
        name="Data Centers",
        name_ko="\ub370\uc774\ud130\uc13c\ud130",
        description="Data-center REITs, power, networking, and AI infrastructure suppliers.",
        sector="Technology",
        sector_ko="\ub370\uc774\ud130\uc13c\ud130",
        rows=(
            ("EQIX", "Equinix", "Equinix", "NASDAQ", "overseas", "USD", "large-cap"),
            ("DLR", "Digital Realty", "Digital Realty", "NYSE", "overseas", "USD", "large-cap"),
            ("AMT", "American Tower", "American Tower", "NYSE", "overseas", "USD", "large-cap"),
            ("VRT", "Vertiv", "Vertiv", "NYSE", "overseas", "USD", "large-cap"),
            ("ETN", "Eaton", "Eaton", "NYSE", "overseas", "USD", "large-cap"),
            ("ANET", "Arista Networks", "Arista Networks", "NYSE", "overseas", "USD", "large-cap"),
            (
                "SMCI",
                "Super Micro Computer",
                "Super Micro Computer",
                "NASDAQ",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "DELL",
                "Dell Technologies",
                "Dell Technologies",
                "NYSE",
                "overseas",
                "USD",
                "large-cap",
            ),
            ("NVDA", "NVIDIA Corp.", "NVIDIA Corp.", "NASDAQ", "overseas", "USD", "mega-cap"),
            ("AVGO", "Broadcom Inc.", "Broadcom Inc.", "NASDAQ", "overseas", "USD", "mega-cap"),
        ),
    ),
    _additional_theme(
        key="nuclear-energy",
        name="Nuclear Energy",
        name_ko="\uc6d0\uc804/\uc6b0\ub77c\ub284",
        description="Nuclear operators, uranium, SMR, and nuclear-service companies.",
        sector="Energy",
        sector_ko="\uc6d0\uc804/\uc6b0\ub77c\ub284",
        rows=(
            (
                "CEG",
                "Constellation Energy",
                "Constellation Energy",
                "NASDAQ",
                "overseas",
                "USD",
                "large-cap",
            ),
            ("VST", "Vistra", "Vistra", "NYSE", "overseas", "USD", "large-cap"),
            ("CCJ", "Cameco", "Cameco", "NYSE", "overseas", "USD", "large-cap"),
            (
                "BWXT",
                "BWX Technologies",
                "BWX Technologies",
                "NYSE",
                "overseas",
                "USD",
                "large-cap",
            ),
            ("SMR", "NuScale Power", "NuScale Power", "NYSE", "overseas", "USD", "large-cap"),
            ("OKLO", "Oklo", "Oklo", "NYSE", "overseas", "USD", "large-cap"),
            ("LEU", "Centrus Energy", "Centrus Energy", "NYSE", "overseas", "USD", "large-cap"),
            (
                "UEC",
                "Uranium Energy",
                "Uranium Energy",
                "NYSEAMERICAN",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "URA",
                "Global X Uranium ETF",
                "Global X Uranium ETF",
                "NYSEARCA",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "NLR",
                "VanEck Uranium and Nuclear ETF",
                "VanEck Uranium and Nuclear ETF",
                "NYSEARCA",
                "overseas",
                "USD",
                "large-cap",
            ),
        ),
    ),
    _additional_theme(
        key="robotics-humanoids",
        name="Robotics and Humanoids",
        name_ko="\ub85c\ubd07/\ud734\uba38\ub178\uc774\ub4dc",
        description="Surgical robotics, factory automation, humanoid robotics, and robotics ETFs.",
        sector="Technology",
        sector_ko="\ub85c\ubd07/\ud734\uba38\ub178\uc774\ub4dc",
        rows=(
            (
                "ISRG",
                "Intuitive Surgical",
                "Intuitive Surgical",
                "NASDAQ",
                "overseas",
                "USD",
                "large-cap",
            ),
            ("TSLA", "Tesla", "Tesla", "NASDAQ", "overseas", "USD", "mega-cap"),
            ("TER", "Teradyne", "Teradyne", "NASDAQ", "overseas", "USD", "large-cap"),
            ("SYM", "Symbotic", "Symbotic", "NASDAQ", "overseas", "USD", "large-cap"),
            ("PATH", "UiPath", "UiPath", "NYSE", "overseas", "USD", "large-cap"),
            ("ABBNY", "ABB ADR", "ABB ADR", "OTC", "overseas", "USD", "large-cap"),
            ("FANUY", "Fanuc ADR", "Fanuc ADR", "OTC", "overseas", "USD", "large-cap"),
            (
                "ROBO",
                "ROBO Global Robotics ETF",
                "ROBO Global Robotics ETF",
                "NYSEARCA",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "BOTZ",
                "Global X Robotics ETF",
                "Global X Robotics ETF",
                "NASDAQ",
                "overseas",
                "USD",
                "large-cap",
            ),
            ("IRBT", "iRobot", "iRobot", "NASDAQ", "overseas", "USD", "large-cap"),
        ),
    ),
    _additional_theme(
        key="defense",
        name="Defense",
        name_ko="\ubc29\uc0b0",
        description="Defense primes, shipbuilding, security software, and tactical systems.",
        sector="Industrials",
        sector_ko="\ubc29\uc0b0",
        rows=(
            ("RTX", "RTX", "RTX", "NYSE", "overseas", "USD", "large-cap"),
            ("LMT", "Lockheed Martin", "Lockheed Martin", "NYSE", "overseas", "USD", "large-cap"),
            ("NOC", "Northrop Grumman", "Northrop Grumman", "NYSE", "overseas", "USD", "large-cap"),
            ("GD", "General Dynamics", "General Dynamics", "NYSE", "overseas", "USD", "large-cap"),
            (
                "LHX",
                "L3Harris Technologies",
                "L3Harris Technologies",
                "NYSE",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "HII",
                "Huntington Ingalls",
                "Huntington Ingalls",
                "NYSE",
                "overseas",
                "USD",
                "large-cap",
            ),
            ("LDOS", "Leidos", "Leidos", "NYSE", "overseas", "USD", "large-cap"),
            ("TXT", "Textron", "Textron", "NYSE", "overseas", "USD", "large-cap"),
            ("KTOS", "Kratos Defense", "Kratos Defense", "NASDAQ", "overseas", "USD", "large-cap"),
            (
                "ITA",
                "iShares US Aerospace & Defense ETF",
                "iShares US Aerospace & Defense ETF",
                "BATS",
                "overseas",
                "USD",
                "large-cap",
            ),
        ),
    ),
    _additional_theme(
        key="aerospace-space",
        name="Aerospace and Space",
        name_ko="\uc6b0\uc8fc\ud56d\uacf5",
        description="Aircraft, engines, defense space systems, launch, satellite, and space ETFs.",
        sector="Industrials",
        sector_ko="\uc6b0\uc8fc\ud56d\uacf5",
        rows=(
            ("BA", "Boeing", "Boeing", "NYSE", "overseas", "USD", "large-cap"),
            ("AIR", "Airbus ADR", "Airbus ADR", "OTC", "overseas", "USD", "large-cap"),
            ("GE", "GE Aerospace", "GE Aerospace", "NYSE", "overseas", "USD", "large-cap"),
            ("RTX", "RTX", "RTX", "NYSE", "overseas", "USD", "large-cap"),
            ("LMT", "Lockheed Martin", "Lockheed Martin", "NYSE", "overseas", "USD", "large-cap"),
            ("NOC", "Northrop Grumman", "Northrop Grumman", "NYSE", "overseas", "USD", "large-cap"),
            ("RKLB", "Rocket Lab", "Rocket Lab", "NASDAQ", "overseas", "USD", "large-cap"),
            (
                "ASTS",
                "AST SpaceMobile",
                "AST SpaceMobile",
                "NASDAQ",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "IRDM",
                "Iridium Communications",
                "Iridium Communications",
                "NASDAQ",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "UFO",
                "Procure Space ETF",
                "Procure Space ETF",
                "NASDAQ",
                "overseas",
                "USD",
                "large-cap",
            ),
        ),
    ),
    _additional_theme(
        key="biotech",
        name="Biotech",
        name_ko="\ubc14\uc774\uc624",
        description="Large-cap biotech, genomics, RNA, and gene-editing names.",
        sector="Healthcare",
        sector_ko="\ubc14\uc774\uc624",
        rows=(
            ("AMGN", "Amgen", "Amgen", "NASDAQ", "overseas", "USD", "large-cap"),
            (
                "GILD",
                "Gilead Sciences",
                "Gilead Sciences",
                "NASDAQ",
                "overseas",
                "USD",
                "large-cap",
            ),
            ("REGN", "Regeneron", "Regeneron", "NASDAQ", "overseas", "USD", "large-cap"),
            (
                "VRTX",
                "Vertex Pharmaceuticals",
                "Vertex Pharmaceuticals",
                "NASDAQ",
                "overseas",
                "USD",
                "large-cap",
            ),
            ("MRNA", "Moderna", "Moderna", "NASDAQ", "overseas", "USD", "large-cap"),
            ("BIIB", "Biogen", "Biogen", "NASDAQ", "overseas", "USD", "large-cap"),
            ("ILMN", "Illumina", "Illumina", "NASDAQ", "overseas", "USD", "large-cap"),
            ("BNTX", "BioNTech", "BioNTech", "NASDAQ", "overseas", "USD", "large-cap"),
            ("ALNY", "Alnylam", "Alnylam", "NASDAQ", "overseas", "USD", "large-cap"),
            (
                "CRSP",
                "CRISPR Therapeutics",
                "CRISPR Therapeutics",
                "NASDAQ",
                "overseas",
                "USD",
                "large-cap",
            ),
        ),
    ),
    _additional_theme(
        key="blockchain",
        name="Blockchain",
        name_ko="\ube14\ub85d\uccb4\uc778",
        description="Crypto exchanges, bitcoin treasury exposure, miners, and blockchain ETFs.",
        sector="Financials",
        sector_ko="\ube14\ub85d\uccb4\uc778",
        rows=(
            ("COIN", "Coinbase", "Coinbase", "NASDAQ", "overseas", "USD", "large-cap"),
            ("MSTR", "MicroStrategy", "MicroStrategy", "NASDAQ", "overseas", "USD", "large-cap"),
            ("MARA", "MARA Holdings", "MARA Holdings", "NASDAQ", "overseas", "USD", "large-cap"),
            ("RIOT", "Riot Platforms", "Riot Platforms", "NASDAQ", "overseas", "USD", "large-cap"),
            ("CLSK", "CleanSpark", "CleanSpark", "NASDAQ", "overseas", "USD", "large-cap"),
            ("HUT", "Hut 8", "Hut 8", "NASDAQ", "overseas", "USD", "large-cap"),
            ("BITF", "Bitfarms", "Bitfarms", "NASDAQ", "overseas", "USD", "large-cap"),
            ("GLXY", "Galaxy Digital", "Galaxy Digital", "NASDAQ", "overseas", "USD", "large-cap"),
            (
                "BLOK",
                "Amplify Transformational Data ETF",
                "Amplify Transformational Data ETF",
                "NYSEARCA",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "IBIT",
                "iShares Bitcoin Trust ETF",
                "iShares Bitcoin Trust ETF",
                "NASDAQ",
                "overseas",
                "USD",
                "large-cap",
            ),
        ),
    ),
    _additional_theme(
        key="us-inverse-etfs",
        name="US Inverse ETFs",
        name_ko="\ubbf8\uad6d \uc778\ubc84\uc2a4 ETF",
        description="US inverse and leveraged inverse ETFs for short-term defensive tests.",
        sector="Inverse ETFs",
        sector_ko="\ubbf8\uad6d \uc778\ubc84\uc2a4 ETF",
        rows=(
            (
                "SH",
                "ProShares Short S&P500",
                "ProShares Short S&P500",
                "NYSEARCA",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "PSQ",
                "ProShares Short QQQ",
                "ProShares Short QQQ",
                "NYSEARCA",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "DOG",
                "ProShares Short Dow30",
                "ProShares Short Dow30",
                "NYSEARCA",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "SDS",
                "ProShares UltraShort S&P500",
                "ProShares UltraShort S&P500",
                "NYSEARCA",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "QID",
                "ProShares UltraShort QQQ",
                "ProShares UltraShort QQQ",
                "NYSEARCA",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "SQQQ",
                "ProShares UltraPro Short QQQ",
                "ProShares UltraPro Short QQQ",
                "NASDAQ",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "SPXU",
                "ProShares UltraPro Short S&P500",
                "ProShares UltraPro Short S&P500",
                "NYSEARCA",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "TZA",
                "Direxion Daily Small Cap Bear 3X",
                "Direxion Daily Small Cap Bear 3X",
                "NYSEARCA",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "SOXS",
                "Direxion Daily Semiconductor Bear 3X",
                "Direxion Daily Semiconductor Bear 3X",
                "NYSEARCA",
                "overseas",
                "USD",
                "large-cap",
            ),
            (
                "LABD",
                "Direxion Daily S&P Biotech Bear 3X",
                "Direxion Daily S&P Biotech Bear 3X",
                "NYSEARCA",
                "overseas",
                "USD",
                "large-cap",
            ),
        ),
    ),
    _additional_theme(
        key="korea-inverse-etfs",
        name="Korea Inverse ETFs",
        name_ko="\uad6d\ub0b4 \uc778\ubc84\uc2a4 ETF",
        description="Korean inverse and leveraged inverse ETFs for defensive paper-trading tests.",
        sector="Inverse ETFs",
        sector_ko="\uad6d\ub0b4 \uc778\ubc84\uc2a4 ETF",
        rows=(
            ("114800", "KODEX Inverse", "KODEX Inverse", "KOSPI", "domestic", "KRW", "large-cap"),
            (
                "252670",
                "KODEX 200 Futures Inverse 2X",
                "KODEX 200 Futures Inverse 2X",
                "KOSPI",
                "domestic",
                "KRW",
                "large-cap",
            ),
            (
                "251340",
                "KODEX KOSDAQ150 Futures Inverse",
                "KODEX KOSDAQ150 Futures Inverse",
                "KOSPI",
                "domestic",
                "KRW",
                "large-cap",
            ),
            ("123310", "TIGER Inverse", "TIGER Inverse", "KOSPI", "domestic", "KRW", "large-cap"),
            (
                "252710",
                "TIGER 200 Futures Inverse 2X",
                "TIGER 200 Futures Inverse 2X",
                "KOSPI",
                "domestic",
                "KRW",
                "large-cap",
            ),
            (
                "250780",
                "TIGER KOSDAQ150 Futures Inverse",
                "TIGER KOSDAQ150 Futures Inverse",
                "KOSPI",
                "domestic",
                "KRW",
                "large-cap",
            ),
            (
                "253160",
                "ARIRANG 200 Futures Inverse 2X",
                "ARIRANG 200 Futures Inverse 2X",
                "KOSPI",
                "domestic",
                "KRW",
                "large-cap",
            ),
            (
                "253230",
                "KOSEF 200 Futures Inverse 2X",
                "KOSEF 200 Futures Inverse 2X",
                "KOSPI",
                "domestic",
                "KRW",
                "large-cap",
            ),
            (
                "252420",
                "KBSTAR 200 Futures Inverse 2X",
                "KBSTAR 200 Futures Inverse 2X",
                "KOSPI",
                "domestic",
                "KRW",
                "large-cap",
            ),
            (
                "291610",
                "KOSEF KOSDAQ150 Futures Inverse",
                "KOSEF KOSDAQ150 Futures Inverse",
                "KOSPI",
                "domestic",
                "KRW",
                "large-cap",
            ),
        ),
    ),
)

THEME_UNIVERSE = (*THEME_UNIVERSE, *ADDITIONAL_THEME_UNIVERSE)


def get_theme_universe(
    mode: str = "core",
    include_extended: bool = False,
) -> ThemeUniverseResponse:
    resolved_mode = _normalize_theme_mode(mode)
    include_all = include_extended or resolved_mode == "all"

    themes_by_key = {theme.key: theme for theme in THEME_UNIVERSE}
    selected: list[ThemeUniverse] = [
        themes_by_key[key] for key in _CORE_THEME_KEYS if key in themes_by_key
    ]

    if include_all:
        selected.extend(
            theme for theme in THEME_UNIVERSE if theme.key not in set(_CORE_THEME_KEYS)
        )

    return ThemeUniverseResponse(
        count=len(selected),
        mode="all" if include_all else "core",
        refreshed_at=datetime.now(tz=UTC).isoformat(),
        themes=selected,
        notes=[
            f"Theme universe mode: {'all' if include_all else 'core'}.",
            "Market-cap ranks are curated metadata, not live market data.",
        ],
    )
