from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

Region = Literal["domestic", "overseas"]


class UniverseHolding(BaseModel):
    symbol: str
    name: str
    local_name: str
    market: str
    region: Region
    currency: Literal["KRW", "USD"]
    sector: str
    sector_ko: str
    market_cap_rank: int
    market_cap_bucket: Literal["mega-cap", "large-cap"]


class ThemeUniverse(BaseModel):
    key: str
    name: str
    description: str
    sector: str
    top_market_cap: list[UniverseHolding]


class ThemeUniverseResponse(BaseModel):
    source: str = "MCBot curated universe"
    count: int
    themes: list[ThemeUniverse]
    notes: list[str] = Field(default_factory=list)


THEME_UNIVERSE: tuple[ThemeUniverse, ...] = (
    ThemeUniverse(
        key="semiconductors",
        name="Semiconductors",
        description="Chip designers, foundries, and key equipment names.",
        sector="Technology",
        top_market_cap=[
            UniverseHolding(
                symbol="NVDA",
                name="NVIDIA Corp.",
                local_name="NVIDIA Corp.",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=1,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="AVGO",
                name="Broadcom Inc.",
                local_name="Broadcom Inc.",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=2,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="TSM",
                name="Taiwan Semiconductor",
                local_name="Taiwan Semiconductor",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=3,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="ASML",
                name="ASML Holding",
                local_name="ASML Holding",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=4,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="AMD",
                name="Advanced Micro Devices",
                local_name="Advanced Micro Devices",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=5,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="QCOM",
                name="Qualcomm Inc.",
                local_name="Qualcomm Inc.",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=6,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="TXN",
                name="Texas Instruments",
                local_name="Texas Instruments",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=7,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="MU",
                name="Micron Technology",
                local_name="Micron Technology",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=8,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="AMAT",
                name="Applied Materials",
                local_name="Applied Materials",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=9,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="LRCX",
                name="Lam Research",
                local_name="Lam Research",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Semiconductors",
                sector_ko="Semiconductors",
                market_cap_rank=10,
                market_cap_bucket="large-cap",
            ),
        ],
    ),
    ThemeUniverse(
        key="ai-platforms",
        name="AI Platforms",
        description="Model platforms, cloud infrastructure, and workflow software.",
        sector="Technology",
        top_market_cap=[
            UniverseHolding(
                symbol="MSFT",
                name="Microsoft",
                local_name="Microsoft",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=1,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="AMZN",
                name="Amazon",
                local_name="Amazon",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=2,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="GOOGL",
                name="Alphabet Class A",
                local_name="Alphabet Class A",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=3,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="META",
                name="Meta Platforms",
                local_name="Meta Platforms",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=4,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="ORCL",
                name="Oracle",
                local_name="Oracle",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=5,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="CRM",
                name="Salesforce",
                local_name="Salesforce",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=6,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="NOW",
                name="ServiceNow",
                local_name="ServiceNow",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=7,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="ADBE",
                name="Adobe",
                local_name="Adobe",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=8,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="SNOW",
                name="Snowflake",
                local_name="Snowflake",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=9,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="IBM",
                name="IBM",
                local_name="IBM",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="AI Platforms",
                sector_ko="AI Platforms",
                market_cap_rank=10,
                market_cap_bucket="large-cap",
            ),
        ],
    ),
    ThemeUniverse(
        key="ev-batteries",
        name="EV and Batteries",
        description="Electric vehicle makers, battery tech, and charging infrastructure.",
        sector="Automotive",
        top_market_cap=[
            UniverseHolding(
                symbol="TSLA",
                name="Tesla",
                local_name="Tesla",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=1,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="GM",
                name="General Motors",
                local_name="General Motors",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=2,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="F",
                name="Ford Motor",
                local_name="Ford Motor",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=3,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="NIO",
                name="NIO Inc.",
                local_name="NIO Inc.",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=4,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="XPEV",
                name="XPeng",
                local_name="XPeng",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=5,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="RIVN",
                name="Rivian",
                local_name="Rivian",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=6,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="LCID",
                name="Lucid Group",
                local_name="Lucid Group",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=7,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="QS",
                name="QuantumScape",
                local_name="QuantumScape",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=8,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="BE",
                name="Bloom Energy",
                local_name="Bloom Energy",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=9,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="PLUG",
                name="Plug Power",
                local_name="Plug Power",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="EV and Batteries",
                sector_ko="EV and Batteries",
                market_cap_rank=10,
                market_cap_bucket="large-cap",
            ),
        ],
    ),
    ThemeUniverse(
        key="healthcare-innovation",
        name="Healthcare Innovation",
        description="Large-cap healthcare leaders and medical technology names.",
        sector="Healthcare",
        top_market_cap=[
            UniverseHolding(
                symbol="LLY",
                name="Eli Lilly",
                local_name="Eli Lilly",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=1,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="UNH",
                name="UnitedHealth Group",
                local_name="UnitedHealth Group",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=2,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="JNJ",
                name="Johnson & Johnson",
                local_name="Johnson & Johnson",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=3,
                market_cap_bucket="mega-cap",
            ),
            UniverseHolding(
                symbol="ABBV",
                name="AbbVie",
                local_name="AbbVie",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=4,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="MRK",
                name="Merck",
                local_name="Merck",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=5,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="NVO",
                name="Novo Nordisk",
                local_name="Novo Nordisk",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=6,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="TMO",
                name="Thermo Fisher Scientific",
                local_name="Thermo Fisher Scientific",
                market="NYSE",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=7,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="ISRG",
                name="Intuitive Surgical",
                local_name="Intuitive Surgical",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=8,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="AMGN",
                name="Amgen",
                local_name="Amgen",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=9,
                market_cap_bucket="large-cap",
            ),
            UniverseHolding(
                symbol="GILD",
                name="Gilead Sciences",
                local_name="Gilead Sciences",
                market="NASDAQ",
                region="overseas",
                currency="USD",
                sector="Healthcare Innovation",
                sector_ko="Healthcare Innovation",
                market_cap_rank=10,
                market_cap_bucket="large-cap",
            ),
        ],
    ),
)


def get_theme_universe() -> ThemeUniverseResponse:
    return ThemeUniverseResponse(
        count=len(THEME_UNIVERSE),
        themes=list(THEME_UNIVERSE),
        notes=[
            "Static first-pass universe for dashboard layout and theme strategy.",
            "Market-cap ranks are curated metadata, not live market data.",
        ],
    )
